version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: E01
    environment:
    - node.name=E01
    - cluster.name=E01-cluster
    - ELASTIC_PASSWORD=otakucraft123
    - xpack.security.enabled=true
    - discovery.type=single-node
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
    volumes:
    - dataE01:/usr/share/elasticsearch/data
    ports:
    - 9200:9200
    - 9300:9300
    networks:
    - elastic_net
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.3
    container_name: K01
    environment:
      - SERVER_NAME="K01"
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=otakucraft123
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
    - dataK01:/usr/share/kibana/config
    ports:
    - 5601:5601
    networks:
    - elastic_net
    depends_on:
    - elasticsearch
volumes:
  dataE01:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$PWD/elasticsearch_data'
  dataK01:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$PWD/kibana_data'
networks:
  elastic_net:
    name: elastic_net
    ipam:
      config:
        - subnet: 172.124.12.0/24
          gateway: 172.124.12.1
